Update set_pipeline
- do not use random name
- fix user name regex

Signed-off-by: Tony Wong <twong@pivotal.io>

diff --git a/set_pipeline b/set_pipeline
--- a/set_pipeline
+++ b/set_pipeline
@@ -66,11 +66,12 @@ main() {
   local current_branch_regex='-current-branch$'
   if [[ "${pipeline_name}" =~ $current_branch_regex ]]; then
     branch_name="${2:-$branch_name}"
-    git_username=$(git config user.email | awk -F'=' '{print $2}' | awk -F'@' '{print $1}' | xargs)
+    git_username=$(git config user.email | awk -F'@' '{print $1}' | xargs)
     if [ ! -z "$git_username" ]; then
       pipeline_name="${pipeline_name}-${git_username}"
     else
-      pipeline_name="${pipeline_name}-${RANDOM}"
+      echo "Error: couldn't find git config user.email"
+      exit 1
     fi
   fi
 
